services:
  iot-exhook:
    image: registry.cn-guangzhou.aliyuncs.com/sing-hub/xwk-iot-exhook:latest
    env_file:
      - .env
    container_name: ctn-exhook
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./xwk-iot-exhook/logs/:/app/logs
    networks:
      - pre_xwk_network